<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CloudFlow.Workers.Aws-4bf35ded-c274-43d8-b269-9f9556a53790</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.4" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
    <PackageReference Include="Amazon.Lambda.Core" Version="3.3.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="3.1.1" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="3.0.1" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudFlow.Core\CloudFlow.Core.csproj" />
    <ProjectReference Include="..\CloudFlow.Infrastructure.Aws\CloudFlow.Infrastructure.Aws.csproj" />
  </ItemGroup>
</Project>
