<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.4" />
    <PackageReference Include="AWSSDK.ApiGatewayManagementApi" Version="4.0.100.4" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.4" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.100.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudFlow.Core\CloudFlow.Core.csproj" />
  </ItemGroup>
</Project>
