services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - CloudProvider=${CLOUD_PROVIDER}
      - DemoModeEnabled=${DEMO_MODE_ENABLED}
      - AWS__Region=${AWS_REGION}
      - AWS__AccessKey=${AWS_ACCESS_KEY_ID}
      - AWS__SecretKey=${AWS_SECRET_ACCESS_KEY}
      - AWS__DynamoDB__ServiceUrl=${AWS_DYNAMODB_SERVICE_URL}
      - AWS__WebSocket__ServiceUrl=${AWS_WEBSOCKET_SERVICE_URL}
      - AWS__WebSocket__PublicUrl=${AWS_WEBSOCKET_PUBLIC_URL}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro