name: cloudflow

services:
  api:
    container_name: cloudflow-api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: CloudFlow.Api/Dockerfile
    networks:
      - cloudflow-network

  workers:
    container_name: cloudflow-workers
    image: ${DOCKER_REGISTRY-}workers
    build:
      context: .
      dockerfile: CloudFlow.Workers.Aws/Dockerfile
    networks:
      - cloudflow-network

  dynamodb:
    container_name: cloudflow-dynamodb
    image: amazon/dynamodb-local:3.3.1
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    working_dir: /home/dynamodblocal
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - cloudflow-network

volumes:
  dynamodb-data:

networks:
  cloudflow-network:
    driver: bridge

